# python3 playbook.py -i ../playbook/example-playbook.yaml -o temp.py
- name: example
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add two Numbers together
      open_ssh:
        host: 192.168.3.25
        usr: root
        passwd: cDe3@wsx
      timeout: timeout_quit

    - name: Open Pod
      open_pod:
      timeout: timeout_quit
    
    - name: ls -l /usr/shunyi --color=never
      invoke_shell:
              cmd: ls -al /usr/shunyi/ansible-workspace/
      register: return_value

    - name: Checks if return value equals to \'~]# \'
      debug:
        msg: return_value
      when: return_value.endswith('~]# ')
      notify: 
         - for
         - Print list
        #  - continue_warning
        #  - quit_procedure

    - name: ssh close
      close_ssh:

  handlers:
    - name: quit_procedure
      quit_procedure: 
    
    - name: continue_warning
      continue_warning: 
        msg: '跳过并继续'

    - name: for
      invoke_shell:
              cmd: for i in {1..100}; do echo $i; done
      register: list2

    - name: Print list
      debug:
        msg: list2
