# python3 playbook.py -i ../playbook/example-playbook.yaml -o temp.py
- name: example
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: connect over ssh
      open_ssh:
        host: 10.10.10.10
        usr: root
        passwd: cDe3@wsx0n
      timeout: timeout_quit

    - name: ssh -i /root/.ssh/5g_lab_key eccd@10.221.221.221
      invoke_shell:
        cmd: ssh -i /root/.ssh/5g_lab_key eccd@10.221.221.221
      timeout: timeout_quit

    - name: kubectl exec -n pcc1 -ti eric-pc-mm-controller-0 -- tcsh
      invoke_shell:
              cmd: kubectl exec -n pcc1 -ti eric-pc-mm-controller-0 -- tcsh
      register: return_value

    - name: Check 1
      quit_procedure:  
      when:  return_value.endswith(('=== rp-pcc-1 root@eric-pc-mm-controller-0 ANCB / *# '))

    - name: su system_admin
      invoke_shell:
        cmd: su system_admin
      register: return_value

    - name: Check 2
      quit_procedure:  
      when:  return_value.endswith(('=== rp-pcc-1 system_admin@eric-pc-mm-controller-0 ANCB / *# '))

    - name: health_check.pl -l
      invoke_shell:
        cmd: health_check.pl -l

    - name: quit_shell - exit
      quit_shell:
      register: return_value
    
    - name: Check 3
      quit_procedure:  
      when:  return_value.endswith(('=== rp-pcc-1 root@eric-pc-mm-controller-0 ANCB / *# '))

    - name: quit_shell - logout
      quit_shell:
      register: return_value
 
    - name: Check 4
      quit_procedure:  
      when: return_value.endswith(('eccd@director-0-eccd1:~> '))

    - name: close_channel
      close_channel:
  